In [ ]:
# %pip install catboost optuna

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import KFold, StratifiedKFold, train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.impute import SimpleImputer

import xgboost as xgb
import lightgbm as lgb
import catboost as cb

import optuna
from optuna.samplers import TPESampler

import os
# Set random seed for reproducibility
RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

In [ ]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

train.head()

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,X11,Y
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [ ]:
# Check missing values
train.isnull().sum()
test.isnull().sum()

X1       0
X2     457
X3       0
X4       0
X5       0
X6       0
X7       0
X8       0
X9     699
X10      0
X11      0
dtype: int64

In [ ]:
column_mapping = {
    'X1': 'Item_Identifier',
    'X2': 'Item_Weight',
    'X3': 'Item_Fat_Content',
    'X4': 'Item_Visibility',
    'X5': 'Item_Type',
    'X6': 'Item_MRP',
    'X7': 'Outlet_Identifier',
    'X8': 'Outlet_Establishment_Year',
    'X9': 'Outlet_Size',
    'X10': 'Outlet_Location_Type',
    'X11': 'Outlet_Type',
    'Y': 'Item_Outlet_Sales'
}

train.rename(columns=column_mapping, inplace=True)
test.rename(columns=column_mapping, inplace=True)

print("Train columns:", train.columns.tolist())
print("Test columns:", test.columns.tolist())
train.head()

Train columns: ['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility', 'Item_Type', 'Item_MRP', 'Outlet_Identifier', 'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Type', 'Item_Outlet_Sales']
Test columns: ['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility', 'Item_Type', 'Item_MRP', 'Outlet_Identifier', 'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Type']

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [ ]:
train['Item_Fat_Content'] = train['Item_Fat_Content'].replace({
    'LF': 'Low Fat',
    'low fat': 'Low Fat',
    'reg': 'Regular'
})
test['Item_Fat_Content'] = test['Item_Fat_Content'].replace({
    'LF': 'Low Fat',
    'low fat': 'Low Fat',
    'reg': 'Regular'
})

print(train['Item_Fat_Content'].value_counts())

Item_Fat_Content
Low Fat    3889
Regular    2111
Name: count, dtype: int64

In [ ]:
outlet_size_mode = train.groupby('Outlet_Type')['Outlet_Size'].agg(lambda x: x.mode()[0] if not x.mode().empty else 'Medium')
train['Outlet_Size'] = train.apply(
    lambda row: outlet_size_mode[row['Outlet_Type']] if pd.isnull(row['Outlet_Size']) else row['Outlet_Size'],
    axis=1
)
test['Outlet_Size'] = test.apply(
    lambda row: outlet_size_mode.get(row['Outlet_Type'], 'Medium') if pd.isnull(row['Outlet_Size']) else row['Outlet_Size'],
    axis=1
)

print(train.isnull().sum())
print(test.isnull().sum())

Item_Identifier                 0
Item_Weight                  1006
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                     0
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64
Item_Identifier                0
Item_Weight                  457
Item_Fat_Content               0
Item_Visibility                0
Item_Type                      0
Item_MRP                       0
Outlet_Identifier              0
Outlet_Establishment_Year      0
Outlet_Size                    0
Outlet_Location_Type           0
Outlet_Type                    0
dtype: int64

In [ ]:
current_year = 2025  # You can also use max year in data (train['Outlet_Establishment_Year'].max())
train['Outlet_Age'] = current_year - train['Outlet_Establishment_Year']
test['Outlet_Age'] = current_year - test['Outlet_Establishment_Year']

In [ ]:
def target_encode(train, test, col, target, folds=5):
    """Apply target encoding with K-fold on train, and map to test using global mean."""
    train_encoded = np.zeros(train.shape[0])
    kf = KFold(n_splits=folds, shuffle=True, random_state=RANDOM_STATE)
    for tr_idx, val_idx in kf.split(train):
        tr, val = train.iloc[tr_idx], train.iloc[val_idx]
        means = tr.groupby(col)[target].mean()
        train_encoded[val_idx] = val[col].map(means).fillna(tr[target].mean())
    # Global mean for test
    global_mean = train.groupby(col)[target].mean()
    test_encoded = test[col].map(global_mean).fillna(train[target].mean())
    return train_encoded, test_encoded

In [ ]:
# 'Item_Identifier' – very high cardinality, but we can encode
train['Item_Id_Enc'], test['Item_Id_Enc'] = target_encode(train, test, 'Item_Identifier', 'Item_Outlet_Sales')

# 'Outlet_Identifier' – also high
train['Outlet_Id_Enc'], test['Outlet_Id_Enc'] = target_encode(train, test, 'Outlet_Identifier', 'Item_Outlet_Sales')

In [ ]:
cat_cols = ['Item_Fat_Content', 'Item_Type', 'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Type']
train = pd.get_dummies(train, columns=cat_cols, drop_first=True)
test = pd.get_dummies(test, columns=cat_cols, drop_first=True)

# Ensure test has same columns as train (align)
train_cols = train.columns
test = test.reindex(columns=train_cols.drop('Item_Outlet_Sales'), fill_value=0)

In [ ]:
train['Item_MRP_Outlet_Age'] = train['Item_MRP'] * train['Outlet_Age']
test['Item_MRP_Outlet_Age'] = test['Item_MRP'] * test['Outlet_Age']

train['Item_Visibility_Weight'] = train['Item_Visibility'] * train['Item_Weight']
test['Item_Visibility_Weight'] = test['Item_Visibility'] * test['Item_Weight']

In [ ]:
train['Visibility_Zero'] = (train['Item_Visibility'] == 0).astype(int)
test['Visibility_Zero'] = (test['Item_Visibility'] == 0).astype(int)
y = train['Item_Outlet_Sales']
y_log = np.log1p(y)

In [ ]:
X = train.drop(['Item_Outlet_Sales', 'Item_Identifier', 'Outlet_Identifier', 'Outlet_Establishment_Year'], axis=1)
X_test = test.drop(['Item_Identifier', 'Outlet_Identifier', 'Outlet_Establishment_Year'], axis=1, errors='ignore')

In [ ]:
def objective_xgb(trial, X, y, cv=5):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 500, 2000, step=100),
        'max_depth': trial.suggest_int('max_depth', 3, 12),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'gamma': trial.suggest_float('gamma', 0, 5),
        'reg_alpha': trial.suggest_float('reg_alpha', 1e-8, 10.0, log=True),
        'reg_lambda': trial.suggest_float('reg_lambda', 1e-8, 10.0, log=True),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'random_state': RANDOM_STATE,
        'tree_method': 'hist',
        'early_stopping_rounds': 50  # Moved here from fit()
    }

    kf = KFold(n_splits=cv, shuffle=True, random_state=RANDOM_STATE)
    scores = []
    for train_idx, val_idx in kf.split(X):
        X_tr, X_val = X.iloc[train_idx], X.iloc[val_idx]
        y_tr, y_val = y.iloc[train_idx], y.iloc[val_idx]

        model = xgb.XGBRegressor(**params)
        # Removed early_stopping_rounds from fit()
        model.fit(X_tr, y_tr, eval_set=[(X_val, y_val)], verbose=False)
        pred = model.predict(X_val)
        score = np.sqrt(mean_squared_error(y_val, pred))
        scores.append(score)

    return np.mean(scores)

study_xgb = optuna.create_study(direction='minimize', sampler=TPESampler(seed=RANDOM_STATE))
study_xgb.optimize(lambda trial: objective_xgb(trial, X, y), n_trials=30, show_progress_bar=True)

print('Best XGBoost trial:', study_xgb.best_trial.params)
print('Best XGBoost CV RMSE:', study_xgb.best_value)

[I 2026-02-20 23:36:19,558] A new study created in memory with name: no-name-859f1a9c-7a33-4a28-a85a-1b083ca8b09f

  0%|          | 0/30 [00:00<?, ?it/s]

[I 2026-02-20 23:36:24,167] Trial 0 finished with value: 1139.9781908711132 and parameters: {'n_estimators': 1000, 'max_depth': 12, 'learning_rate': 0.1205712628744377, 'subsample': 0.7993292420985183, 'colsample_bytree': 0.5780093202212182, 'gamma': 0.7799726016810132, 'reg_alpha': 3.3323645788192616e-08, 'reg_lambda': 0.6245760287469893, 'min_child_weight': 7}. Best is trial 0 with value: 1139.9781908711132.
[I 2026-02-20 23:36:25,095] Trial 1 finished with value: 1115.4368337256776 and parameters: {'n_estimators': 1600, 'max_depth': 3, 'learning_rate': 0.2708160864249968, 'subsample': 0.9162213204002109, 'colsample_bytree': 0.6061695553391381, 'gamma': 0.9091248360355031, 'reg_alpha': 4.4734294104626844e-07, 'reg_lambda': 5.472429642032198e-06, 'min_child_weight': 6}. Best is trial 1 with value: 1115.4368337256776.
[I 2026-02-20 23:36:26,565] Trial 2 finished with value: 1105.8052801816334 and parameters: {'n_estimators': 1100, 'max_depth': 5, 'learning_rate': 0.08012737503998542, 'subsample': 0.569746930326021, 'colsample_bytree': 0.6460723242676091, 'gamma': 1.8318092164684585, 'reg_alpha': 0.00012724181576752517, 'reg_lambda': 0.1165691561324743, 'min_child_weight': 2}. Best is trial 2 with value: 1105.8052801816334.
[I 2026-02-20 23:36:36,132] Trial 3 finished with value: 1108.4343108623532 and parameters: {'n_estimators': 1300, 'max_depth': 8, 'learning_rate': 0.011711509955524094, 'subsample': 0.8037724259507192, 'colsample_bytree': 0.5852620618436457, 'gamma': 0.3252579649263976, 'reg_alpha': 3.4671276804481113, 'reg_lambda': 4.905556676028774, 'min_child_weight': 9}. Best is trial 2 with value: 1105.8052801816334.
[I 2026-02-20 23:36:37,324] Trial 4 finished with value: 1111.0346133262346 and parameters: {'n_estimators': 900, 'max_depth': 3, 'learning_rate': 0.1024932221692416, 'subsample': 0.7200762468698007, 'colsample_bytree': 0.5610191174223894, 'gamma': 2.475884550556351, 'reg_alpha': 2.039373116525212e-08, 'reg_lambda': 1.527156759251193, 'min_child_weight': 3}. Best is trial 2 with value: 1105.8052801816334.
[I 2026-02-20 23:36:39,208] Trial 5 finished with value: 1103.2861708887556 and parameters: {'n_estimators': 1500, 'max_depth': 6, 'learning_rate': 0.05864129169696527, 'subsample': 0.7733551396716398, 'colsample_bytree': 0.5924272277627636, 'gamma': 4.847923138822793, 'reg_alpha': 0.09466630153726856, 'reg_lambda': 2.854239907497756, 'min_child_weight': 9}. Best is trial 5 with value: 1103.2861708887556.
[I 2026-02-20 23:36:51,136] Trial 6 finished with value: 1114.7554770255786 and parameters: {'n_estimators': 1400, 'max_depth': 12, 'learning_rate': 0.01351182947645082, 'subsample': 0.5979914312095727, 'colsample_bytree': 0.522613644455269, 'gamma': 1.6266516538163218, 'reg_alpha': 3.148441347423712e-05, 'reg_lambda': 2.7678419414850017e-06, 'min_child_weight': 9}. Best is trial 5 with value: 1103.2861708887556.
[I 2026-02-20 23:36:52,750] Trial 7 finished with value: 1111.6520689692193 and parameters: {'n_estimators': 1000, 'max_depth': 5, 'learning_rate': 0.06333268775321842, 'subsample': 0.5704621124873813, 'colsample_bytree': 0.9010984903770198, 'gamma': 0.3727532183988541, 'reg_alpha': 7.620481786158549, 'reg_lambda': 0.08916674715636537, 'min_child_weight': 2}. Best is trial 5 with value: 1103.2861708887556.
[I 2026-02-20 23:36:55,656] Trial 8 finished with value: 1135.2291365894698 and parameters: {'n_estimators': 500, 'max_depth': 11, 'learning_rate': 0.11069143219393454, 'subsample': 0.8645035840204937, 'colsample_bytree': 0.8856351733429728, 'gamma': 0.3702232586704518, 'reg_alpha': 1.683416412018213e-05, 'reg_lambda': 1.1036250149900698e-07, 'min_child_weight': 9}. Best is trial 5 with value: 1103.2861708887556.
[I 2026-02-20 23:37:02,659] Trial 9 finished with value: 1104.6782614696554 and parameters: {'n_estimators': 1400, 'max_depth': 6, 'learning_rate': 0.012413189635294229, 'subsample': 0.6554911608578311, 'colsample_bytree': 0.6625916610133735, 'gamma': 3.64803089169032, 'reg_alpha': 0.005470376807480391, 'reg_lambda': 0.9658611176861268, 'min_child_weight': 5}. Best is trial 5 with value: 1103.2861708887556.
[I 2026-02-20 23:37:06,918] Trial 10 finished with value: 1122.973797341701 and parameters: {'n_estimators': 2000, 'max_depth': 9, 'learning_rate': 0.03001215871999436, 'subsample': 0.9661451709558936, 'colsample_bytree': 0.7640858921203038, 'gamma': 4.538323976412588, 'reg_alpha': 0.03743708770436097, 'reg_lambda': 0.002861549446231723, 'min_child_weight': 10}. Best is trial 5 with value: 1103.2861708887556.
[I 2026-02-20 23:37:09,666] Trial 11 finished with value: 1108.1605782995516 and parameters: {'n_estimators': 1800, 'max_depth': 6, 'learning_rate': 0.03057610208137913, 'subsample': 0.674024292456548, 'colsample_bytree': 0.7171781358782056, 'gamma': 4.699069646835413, 'reg_alpha': 0.014865329302749829, 'reg_lambda': 0.0029151336209232927, 'min_child_weight': 5}. Best is trial 5 with value: 1103.2861708887556.
[I 2026-02-20 23:37:14,776] Trial 12 finished with value: 1107.1979012596319 and parameters: {'n_estimators': 1500, 'max_depth': 7, 'learning_rate': 0.03338034147970685, 'subsample': 0.6625712669661852, 'colsample_bytree': 0.7085862143808441, 'gamma': 3.6804739106927307, 'reg_alpha': 0.020439174832649013, 'reg_lambda': 8.169040218027703, 'min_child_weight': 4}. Best is trial 5 with value: 1103.2861708887556.
[I 2026-02-20 23:37:20,611] Trial 13 finished with value: 1113.6188992403677 and parameters: {'n_estimators': 1700, 'max_depth': 9, 'learning_rate': 0.019043663167936355, 'subsample': 0.5034237651213853, 'colsample_bytree': 0.7766688519794932, 'gamma': 3.7682059579960896, 'reg_alpha': 0.21585740371692944, 'reg_lambda': 0.01563383800457537, 'min_child_weight': 7}. Best is trial 5 with value: 1103.2861708887556.
[I 2026-02-20 23:37:22,313] Trial 14 finished with value: 1108.3897706096882 and parameters: {'n_estimators': 700, 'max_depth': 5, 'learning_rate': 0.04815035925095873, 'subsample': 0.7547627787608182, 'colsample_bytree': 0.660331865238152, 'gamma': 3.728454237502311, 'reg_alpha': 0.0010695159048720376, 'reg_lambda': 0.0001279792581265537, 'min_child_weight': 7}. Best is trial 5 with value: 1103.2861708887556.
[I 2026-02-20 23:37:25,567] Trial 15 finished with value: 1144.075103377836 and parameters: {'n_estimators': 1200, 'max_depth': 7, 'learning_rate': 0.2702272241241035, 'subsample': 0.6595512711597814, 'colsample_bytree': 0.8211113451678518, 'gamma': 3.107542839654335, 'reg_alpha': 0.0008708586832471307, 'reg_lambda': 0.00015527584009850318, 'min_child_weight': 5}. Best is trial 5 with value: 1103.2861708887556.
[I 2026-02-20 23:37:28,390] Trial 16 finished with value: 1099.789379711854 and parameters: {'n_estimators': 1900, 'max_depth': 4, 'learning_rate': 0.020375616966251724, 'subsample': 0.8366358953823301, 'colsample_bytree': 0.5037938451535127, 'gamma': 4.9076510186844065, 'reg_alpha': 0.33715141993795805, 'reg_lambda': 0.23570372812031762, 'min_child_weight': 1}. Best is trial 16 with value: 1099.789379711854.
[I 2026-02-20 23:37:31,526] Trial 17 finished with value: 1099.983647670459 and parameters: {'n_estimators': 2000, 'max_depth': 4, 'learning_rate': 0.018675578054162322, 'subsample': 0.8534634820806921, 'colsample_bytree': 0.5029085094630523, 'gamma': 4.995314031585572, 'reg_alpha': 0.4154632233270099, 'reg_lambda': 0.03166021514536092, 'min_child_weight': 1}. Best is trial 16 with value: 1099.789379711854.
[I 2026-02-20 23:37:34,541] Trial 18 finished with value: 1100.2946943050094 and parameters: {'n_estimators': 2000, 'max_depth': 4, 'learning_rate': 0.020038260312712813, 'subsample': 0.8582570370967709, 'colsample_bytree': 0.5030567417747024, 'gamma': 4.134336554829186, 'reg_alpha': 0.8274359253130533, 'reg_lambda': 0.014380006926985071, 'min_child_weight': 1}. Best is trial 16 with value: 1099.789379711854.
[I 2026-02-20 23:37:39,385] Trial 19 finished with value: 1100.6462635195558 and parameters: {'n_estimators': 1800, 'max_depth': 4, 'learning_rate': 0.01983528680174693, 'subsample': 0.9956385980717998, 'colsample_bytree': 0.5270619558742973, 'gamma': 4.986766544643718, 'reg_alpha': 0.43520050071377997, 'reg_lambda': 0.08003231537260756, 'min_child_weight': 1}. Best is trial 16 with value: 1099.789379711854.
[I 2026-02-20 23:37:41,246] Trial 20 finished with value: 1105.1199327194217 and parameters: {'n_estimators': 1900, 'max_depth': 4, 'learning_rate': 0.03737366964307479, 'subsample': 0.8622436165562775, 'colsample_bytree': 0.9640514341164361, 'gamma': 4.230732416128281, 'reg_alpha': 1.6579745203970606, 'reg_lambda': 0.0007628495263552133, 'min_child_weight': 3}. Best is trial 16 with value: 1099.789379711854.
[I 2026-02-20 23:37:44,259] Trial 21 finished with value: 1100.0793820126287 and parameters: {'n_estimators': 2000, 'max_depth': 4, 'learning_rate': 0.020056650211730098, 'subsample': 0.8535135564358738, 'colsample_bytree': 0.5001210321182543, 'gamma': 4.253085663206511, 'reg_alpha': 1.2267353814325601, 'reg_lambda': 0.016860375798428723, 'min_child_weight': 1}. Best is trial 16 with value: 1099.789379711854.
[I 2026-02-20 23:37:47,495] Trial 22 finished with value: 1106.2015122354917 and parameters: {'n_estimators': 2000, 'max_depth': 3, 'learning_rate': 0.016664260722259336, 'subsample': 0.913572568892449, 'colsample_bytree': 0.5414139025035237, 'gamma': 4.299597358050555, 'reg_alpha': 0.15159103675997318, 'reg_lambda': 0.016193826977646514, 'min_child_weight': 1}. Best is trial 16 with value: 1099.789379711854.
[I 2026-02-20 23:37:51,833] Trial 23 finished with value: 1100.6305804392885 and parameters: {'n_estimators': 1700, 'max_depth': 4, 'learning_rate': 0.02412343769070911, 'subsample': 0.8153593930772719, 'colsample_bytree': 0.5021383525469627, 'gamma': 3.13300150959628, 'reg_alpha': 8.526001728163994, 'reg_lambda': 0.21549895303348482, 'min_child_weight': 2}. Best is trial 16 with value: 1099.789379711854.
[I 2026-02-20 23:37:57,936] Trial 24 finished with value: 1101.9251422816471 and parameters: {'n_estimators': 1800, 'max_depth': 5, 'learning_rate': 0.01054132650515837, 'subsample': 0.9065204417707206, 'colsample_bytree': 0.6362887384412591, 'gamma': 4.93800551000766, 'reg_alpha': 0.8919679547618774, 'reg_lambda': 0.001929411056558045, 'min_child_weight': 3}. Best is trial 16 with value: 1099.789379711854.
[I 2026-02-20 23:38:03,174] Trial 25 finished with value: 1106.1634609561593 and parameters: {'n_estimators': 1900, 'max_depth': 3, 'learning_rate': 0.015216251287478466, 'subsample': 0.8396055777138034, 'colsample_bytree': 0.54947319674523, 'gamma': 4.4338118395990085, 'reg_alpha': 0.0021440723382598064, 'reg_lambda': 0.017948247171274752, 'min_child_weight': 1}. Best is trial 16 with value: 1099.789379711854.
[I 2026-02-20 23:38:05,757] Trial 26 finished with value: 1101.4043253982645 and parameters: {'n_estimators': 1900, 'max_depth': 4, 'learning_rate': 0.024702182558318995, 'subsample': 0.719601639617028, 'colsample_bytree': 0.6160288147957349, 'gamma': 3.1109913238221525, 'reg_alpha': 0.07905540692839293, 'reg_lambda': 7.356842809183688e-05, 'min_child_weight': 2}. Best is trial 16 with value: 1099.789379711854.
[I 2026-02-20 23:38:08,155] Trial 27 finished with value: 1106.6686919309213 and parameters: {'n_estimators': 1700, 'max_depth': 6, 'learning_rate': 0.04229592447725514, 'subsample': 0.8895164161417118, 'colsample_bytree': 0.5001611342615648, 'gamma': 3.9891847697616623, 'reg_alpha': 0.009327579955292353, 'reg_lambda': 0.3151259553586801, 'min_child_weight': 4}. Best is trial 16 with value: 1099.789379711854.
[I 2026-02-20 23:38:15,756] Trial 28 finished with value: 1119.3281480842638 and parameters: {'n_estimators': 2000, 'max_depth': 8, 'learning_rate': 0.0256775183745965, 'subsample': 0.9437216189094653, 'colsample_bytree': 0.5605057703418533, 'gamma': 2.6747748317766042, 'reg_alpha': 1.7545775042986984, 'reg_lambda': 0.029932183217438825, 'min_child_weight': 1}. Best is trial 16 with value: 1099.789379711854.
[I 2026-02-20 23:38:16,927] Trial 29 finished with value: 1113.7155006389694 and parameters: {'n_estimators': 1600, 'max_depth': 5, 'learning_rate': 0.15921728208236582, 'subsample': 0.8263954555606777, 'colsample_bytree': 0.6926083472226532, 'gamma': 4.597936710218549, 'reg_alpha': 0.19595577788564705, 'reg_lambda': 2.498307427247095e-05, 'min_child_weight': 3}. Best is trial 16 with value: 1099.789379711854.
Best XGBoost trial: {'n_estimators': 1900, 'max_depth': 4, 'learning_rate': 0.020375616966251724, 'subsample': 0.8366358953823301, 'colsample_bytree': 0.5037938451535127, 'gamma': 4.9076510186844065, 'reg_alpha': 0.33715141993795805, 'reg_lambda': 0.23570372812031762, 'min_child_weight': 1}
Best XGBoost CV RMSE: 1099.789379711854

In [ ]:
def objective_lgb(trial, X, y, cv=5):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 500, 2000, step=100),
        'max_depth': trial.suggest_int('max_depth', 3, 15),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('feature_fraction', 0.5, 1.0),
        'reg_alpha': trial.suggest_float('reg_alpha', 1e-8, 10.0, log=True),
        'reg_lambda': trial.suggest_float('reg_lambda', 1e-8, 10.0, log=True),
        'min_child_samples': trial.suggest_int('min_child_samples', 5, 50),
        'random_state': RANDOM_STATE,
        'verbosity': -1,
    }

    kf = KFold(n_splits=cv, shuffle=True, random_state=RANDOM_STATE)
    scores = []
    for train_idx, val_idx in kf.split(X):
        X_tr, X_val = X.iloc[train_idx], X.iloc[val_idx]
        y_tr, y_val = y.iloc[train_idx], y.iloc[val_idx]

        model = lgb.LGBMRegressor(**params)
        # Removed verbose=False which caused the TypeError
        model.fit(X_tr, y_tr, eval_set=[(X_val, y_val)], callbacks=[lgb.early_stopping(50)])
        pred = model.predict(X_val)
        score = np.sqrt(mean_squared_error(y_val, pred))
        scores.append(score)

    return np.mean(scores)

study_lgb = optuna.create_study(direction='minimize', sampler=TPESampler(seed=RANDOM_STATE))
study_lgb.optimize(lambda trial: objective_lgb(trial, X, y), n_trials=30, show_progress_bar=True)

print('Best LightGBM trial:', study_lgb.best_trial.params)
print('Best LightGBM CV RMSE:', study_lgb.best_value)

[I 2026-02-20 23:38:47,918] A new study created in memory with name: no-name-eb4e27f0-37fe-4507-9eea-bca72c9f03a4

  0%|          | 0/30 [00:00<?, ?it/s]

Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[25]	valid_0's l2: 1.22142e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[23]	valid_0's l2: 1.13362e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[24]	valid_0's l2: 1.1156e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[46]	valid_0's l2: 1.20954e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[25]	valid_0's l2: 1.26278e+06
[I 2026-02-20 23:38:48,642] Trial 0 finished with value: 1089.929113036204 and parameters: {'n_estimators': 1000, 'max_depth': 15, 'learning_rate': 0.1205712628744377, 'subsample': 0.7993292420985183, 'feature_fraction': 0.5780093202212182, 'reg_alpha': 2.5348407664333426e-07, 'reg_lambda': 3.3323645788192616e-08, 'min_child_samples': 44}. Best is trial 0 with value: 1089.929113036204.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[246]	valid_0's l2: 1.25115e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[213]	valid_0's l2: 1.13933e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[271]	valid_0's l2: 1.11752e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[338]	valid_0's l2: 1.20789e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[328]	valid_0's l2: 1.28449e+06
[I 2026-02-20 23:38:52,681] Trial 1 finished with value: 1095.092994241501 and parameters: {'n_estimators': 1400, 'max_depth': 12, 'learning_rate': 0.010725209743171997, 'subsample': 0.9849549260809971, 'feature_fraction': 0.9162213204002109, 'reg_alpha': 8.148018307012941e-07, 'reg_lambda': 4.329370014459266e-07, 'min_child_samples': 13}. Best is trial 0 with value: 1089.929113036204.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[65]	valid_0's l2: 1.23434e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[60]	valid_0's l2: 1.14801e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[69]	valid_0's l2: 1.11517e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[98]	valid_0's l2: 1.20382e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[73]	valid_0's l2: 1.28492e+06
[I 2026-02-20 23:38:53,755] Trial 2 finished with value: 1093.8422024360927 and parameters: {'n_estimators': 900, 'max_depth': 9, 'learning_rate': 0.04345454109729477, 'subsample': 0.645614570099021, 'feature_fraction': 0.8059264473611898, 'reg_alpha': 1.8007140198129195e-07, 'reg_lambda': 4.258943089524393e-06, 'min_child_samples': 21}. Best is trial 0 with value: 1089.929113036204.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[143]	valid_0's l2: 1.24451e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[136]	valid_0's l2: 1.13948e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[138]	valid_0's l2: 1.12805e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[180]	valid_0's l2: 1.19907e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[188]	valid_0's l2: 1.27416e+06
[I 2026-02-20 23:38:55,537] Trial 3 finished with value: 1093.789430745504 and parameters: {'n_estimators': 1200, 'max_depth': 13, 'learning_rate': 0.019721610970574007, 'subsample': 0.7571172192068059, 'feature_fraction': 0.7962072844310213, 'reg_alpha': 2.6185068507773707e-08, 'reg_lambda': 0.0029369981104377003, 'min_child_samples': 12}. Best is trial 0 with value: 1089.929113036204.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[8]	valid_0's l2: 1.24308e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[8]	valid_0's l2: 1.15579e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[8]	valid_0's l2: 1.14616e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[9]	valid_0's l2: 1.24273e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[11]	valid_0's l2: 1.31094e+06
[I 2026-02-20 23:38:56,014] Trial 4 finished with value: 1104.0684916631922 and parameters: {'n_estimators': 600, 'max_depth': 15, 'learning_rate': 0.26690431824362526, 'subsample': 0.9041986740582306, 'feature_fraction': 0.6523068845866853, 'reg_alpha': 7.569183361880229e-08, 'reg_lambda': 0.014391207615728067, 'min_child_samples': 25}. Best is trial 0 with value: 1089.929113036204.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[257]	valid_0's l2: 1.229e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[272]	valid_0's l2: 1.14885e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[264]	valid_0's l2: 1.12075e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[376]	valid_0's l2: 1.19857e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[305]	valid_0's l2: 1.27878e+06
[I 2026-02-20 23:38:58,593] Trial 5 finished with value: 1092.9451227790107 and parameters: {'n_estimators': 600, 'max_depth': 9, 'learning_rate': 0.011240768803005551, 'subsample': 0.954660201039391, 'feature_fraction': 0.6293899908000085, 'reg_alpha': 0.009176996354542699, 'reg_lambda': 6.388511557344611e-06, 'min_child_samples': 28}. Best is trial 0 with value: 1089.929113036204.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[9]	valid_0's l2: 1.21621e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[9]	valid_0's l2: 1.13364e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[10]	valid_0's l2: 1.08033e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[22]	valid_0's l2: 1.17815e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[10]	valid_0's l2: 1.26812e+06
[I 2026-02-20 23:38:58,985] Trial 6 finished with value: 1083.6931694652255 and parameters: {'n_estimators': 1300, 'max_depth': 5, 'learning_rate': 0.27051668818999286, 'subsample': 0.8875664116805573, 'feature_fraction': 0.9697494707820946, 'reg_alpha': 1.1309571585271483, 'reg_lambda': 0.002404915432737351, 'min_child_samples': 47}. Best is trial 6 with value: 1083.6931694652255.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[241]	valid_0's l2: 1.21697e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[291]	valid_0's l2: 1.13677e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[269]	valid_0's l2: 1.1056e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[326]	valid_0's l2: 1.17978e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[290]	valid_0's l2: 1.26499e+06
[I 2026-02-20 23:39:01,056] Trial 7 finished with value: 1086.3451124806745 and parameters: {'n_estimators': 600, 'max_depth': 5, 'learning_rate': 0.011662890273931383, 'subsample': 0.6626651653816322, 'feature_fraction': 0.6943386448447411, 'reg_alpha': 2.7678419414850017e-06, 'reg_lambda': 0.28749982347407854, 'min_child_samples': 21}. Best is trial 6 with value: 1083.6931694652255.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[242]	valid_0's l2: 1.23168e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[237]	valid_0's l2: 1.14445e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[205]	valid_0's l2: 1.13003e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[290]	valid_0's l2: 1.19875e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[216]	valid_0's l2: 1.27727e+06
[I 2026-02-20 23:39:05,866] Trial 8 finished with value: 1093.5333079242773 and parameters: {'n_estimators': 900, 'max_depth': 10, 'learning_rate': 0.016149614799999188, 'subsample': 0.9010984903770198, 'feature_fraction': 0.5372753218398854, 'reg_alpha': 7.620481786158549, 'reg_lambda': 0.08916674715636537, 'min_child_samples': 14}. Best is trial 6 with value: 1083.6931694652255.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[21]	valid_0's l2: 1.24892e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[23]	valid_0's l2: 1.14455e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[33]	valid_0's l2: 1.10971e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[31]	valid_0's l2: 1.21911e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[24]	valid_0's l2: 1.29128e+06
[I 2026-02-20 23:39:07,285] Trial 9 finished with value: 1096.259583422409 and parameters: {'n_estimators': 500, 'max_depth': 13, 'learning_rate': 0.11069143219393454, 'subsample': 0.8645035840204937, 'feature_fraction': 0.8856351733429728, 'reg_alpha': 4.638759594322625e-08, 'reg_lambda': 1.683416412018213e-05, 'min_child_samples': 10}. Best is trial 6 with value: 1083.6931694652255.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[15]	valid_0's l2: 1.19831e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[11]	valid_0's l2: 1.13012e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[18]	valid_0's l2: 1.06704e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[21]	valid_0's l2: 1.18391e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[15]	valid_0's l2: 1.24508e+06
[I 2026-02-20 23:39:07,926] Trial 10 finished with value: 1078.9253397914376 and parameters: {'n_estimators': 2000, 'max_depth': 3, 'learning_rate': 0.27047297227177763, 'subsample': 0.5089809378074098, 'feature_fraction': 0.9919371080730973, 'reg_alpha': 1.475649304728371, 'reg_lambda': 4.3444691085504115, 'min_child_samples': 49}. Best is trial 10 with value: 1078.9253397914376.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[11]	valid_0's l2: 1.20912e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[14]	valid_0's l2: 1.13351e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[15]	valid_0's l2: 1.0722e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[19]	valid_0's l2: 1.19117e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[14]	valid_0's l2: 1.25182e+06
[I 2026-02-20 23:39:08,721] Trial 11 finished with value: 1081.9976772270193 and parameters: {'n_estimators': 2000, 'max_depth': 3, 'learning_rate': 0.2923487780601344, 'subsample': 0.5085930751344795, 'feature_fraction': 0.9869601043141659, 'reg_alpha': 8.440370204782143, 'reg_lambda': 7.556243125116112, 'min_child_samples': 49}. Best is trial 10 with value: 1078.9253397914376.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[31]	valid_0's l2: 1.20981e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[25]	valid_0's l2: 1.12969e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[34]	valid_0's l2: 1.0711e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[35]	valid_0's l2: 1.18333e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[30]	valid_0's l2: 1.25483e+06
[I 2026-02-20 23:39:09,351] Trial 12 finished with value: 1081.1440178305606 and parameters: {'n_estimators': 2000, 'max_depth': 3, 'learning_rate': 0.16401332399717275, 'subsample': 0.5018203726540555, 'feature_fraction': 0.9917980782940604, 'reg_alpha': 0.07352386889584706, 'reg_lambda': 9.41874879245652, 'min_child_samples': 38}. Best is trial 10 with value: 1078.9253397914376.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[26]	valid_0's l2: 1.20329e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[25]	valid_0's l2: 1.13056e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[53]	valid_0's l2: 1.079e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[39]	valid_0's l2: 1.17671e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[36]	valid_0's l2: 1.25301e+06
[I 2026-02-20 23:39:10,144] Trial 13 finished with value: 1080.6228246022524 and parameters: {'n_estimators': 2000, 'max_depth': 3, 'learning_rate': 0.13811269358793543, 'subsample': 0.5048579886309473, 'feature_fraction': 0.8731522909801657, 'reg_alpha': 0.018495296668810595, 'reg_lambda': 9.868745464853832, 'min_child_samples': 37}. Best is trial 10 with value: 1078.9253397914376.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[48]	valid_0's l2: 1.21278e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[51]	valid_0's l2: 1.13684e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[48]	valid_0's l2: 1.10629e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[84]	valid_0's l2: 1.19699e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[51]	valid_0's l2: 1.26065e+06
[I 2026-02-20 23:39:11,205] Trial 14 finished with value: 1087.2289740959145 and parameters: {'n_estimators': 1700, 'max_depth': 6, 'learning_rate': 0.06365351244991195, 'subsample': 0.5797654491534234, 'feature_fraction': 0.8705964816373704, 'reg_alpha': 0.0003412830364406516, 'reg_lambda': 0.6255688317185165, 'min_child_samples': 37}. Best is trial 10 with value: 1078.9253397914376.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[15]	valid_0's l2: 1.21633e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[16]	valid_0's l2: 1.13151e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[15]	valid_0's l2: 1.10971e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[15]	valid_0's l2: 1.2074e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[19]	valid_0's l2: 1.28067e+06
[I 2026-02-20 23:39:11,730] Trial 15 finished with value: 1090.1029601576568 and parameters: {'n_estimators': 1700, 'max_depth': 7, 'learning_rate': 0.165245415795992, 'subsample': 0.592847000975673, 'feature_fraction': 0.825401583338162, 'reg_alpha': 0.012983231141306433, 'reg_lambda': 0.00016097275579289857, 'min_child_samples': 38}. Best is trial 10 with value: 1078.9253397914376.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[51]	valid_0's l2: 1.21653e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[66]	valid_0's l2: 1.1238e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[78]	valid_0's l2: 1.07782e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[81]	valid_0's l2: 1.17283e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[66]	valid_0's l2: 1.25777e+06
[I 2026-02-20 23:39:12,208] Trial 16 finished with value: 1081.1429522417452 and parameters: {'n_estimators': 1700, 'max_depth': 3, 'learning_rate': 0.07018279018011765, 'subsample': 0.5646332716363499, 'feature_fraction': 0.9205147917954991, 'reg_alpha': 0.00024334420868072872, 'reg_lambda': 1.4318951998429519, 'min_child_samples': 32}. Best is trial 10 with value: 1078.9253397914376.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[88]	valid_0's l2: 1.22756e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[91]	valid_0's l2: 1.12973e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[88]	valid_0's l2: 1.10464e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[110]	valid_0's l2: 1.19625e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[87]	valid_0's l2: 1.27237e+06
[I 2026-02-20 23:39:13,400] Trial 17 finished with value: 1088.7170792926165 and parameters: {'n_estimators': 1900, 'max_depth': 7, 'learning_rate': 0.03301573993465978, 'subsample': 0.6928119354573563, 'feature_fraction': 0.7660480350338255, 'reg_alpha': 0.2737932637353224, 'reg_lambda': 0.04026246621022625, 'min_child_samples': 44}. Best is trial 10 with value: 1078.9253397914376.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[13]	valid_0's l2: 1.21161e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[14]	valid_0's l2: 1.12748e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[17]	valid_0's l2: 1.08351e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[25]	valid_0's l2: 1.18465e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[22]	valid_0's l2: 1.25603e+06
[I 2026-02-20 23:39:13,826] Trial 18 finished with value: 1082.5246920161735 and parameters: {'n_estimators': 1500, 'max_depth': 5, 'learning_rate': 0.18104829110098095, 'subsample': 0.5514679674687517, 'feature_fraction': 0.8646769007017882, 'reg_alpha': 0.00036390356638230445, 'reg_lambda': 1.731398669918463, 'min_child_samples': 50}. Best is trial 10 with value: 1078.9253397914376.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[35]	valid_0's l2: 1.21431e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[27]	valid_0's l2: 1.12837e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[28]	valid_0's l2: 1.07477e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[47]	valid_0's l2: 1.16873e+06
Training until validation scores don't improve for 50 rounds

In [ ]:
def objective_cat(trial, X, y, cv=5):
    params = {
        'iterations': trial.suggest_int('iterations', 500, 2000, step=100),
        'depth': trial.suggest_int('depth', 3, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'l2_leaf_reg': trial.suggest_float('l2_leaf_reg', 1e-8, 10.0, log=True),
        'bagging_temperature': trial.suggest_float('bagging_temperature', 0, 1),
        'random_seed': RANDOM_STATE,
        'verbose': False,
    }

    kf = KFold(n_splits=cv, shuffle=True, random_state=RANDOM_STATE)
    scores = []
    for train_idx, val_idx in kf.split(X):
        X_tr, X_val = X.iloc[train_idx], X.iloc[val_idx]
        y_tr, y_val = y.iloc[train_idx], y.iloc[val_idx]

        model = cb.CatBoostRegressor(**params)
        model.fit(X_tr, y_tr, eval_set=(X_val, y_val), early_stopping_rounds=50, verbose=False)
        pred = model.predict(X_val)
        score = np.sqrt(mean_squared_error(y_val, pred))
        scores.append(score)

    return np.mean(scores)

study_cat = optuna.create_study(direction='minimize', sampler=TPESampler(seed=RANDOM_STATE))
study_cat.optimize(lambda trial: objective_cat(trial, X, y), n_trials=30, show_progress_bar=True)

print('Best CatBoost trial:', study_cat.best_trial.params)
print('Best CatBoost CV RMSE:', study_cat.best_value)

[I 2026-02-20 23:39:20,255] A new study created in memory with name: no-name-f989c995-8045-498e-9162-eaf20595f75e

  0%|          | 0/30 [00:00<?, ?it/s]

[I 2026-02-20 23:39:32,764] Trial 0 finished with value: 1087.500367799596 and parameters: {'iterations': 1000, 'depth': 10, 'learning_rate': 0.1205712628744377, 'l2_leaf_reg': 0.0024430162614261413, 'bagging_temperature': 0.15601864044243652}. Best is trial 0 with value: 1087.500367799596.
[I 2026-02-20 23:39:33,549] Trial 1 finished with value: 1081.9265861879778 and parameters: {'iterations': 700, 'depth': 3, 'learning_rate': 0.19030368381735815, 'l2_leaf_reg': 0.002570603566117598, 'bagging_temperature': 0.7080725777960455}. Best is trial 1 with value: 1081.9265861879778.
[I 2026-02-20 23:39:43,725] Trial 2 finished with value: 1090.0133526334826 and parameters: {'iterations': 500, 'depth': 10, 'learning_rate': 0.16967533607196555, 'l2_leaf_reg': 8.148018307012941e-07, 'bagging_temperature': 0.18182496720710062}. Best is trial 1 with value: 1081.9265861879778.
[I 2026-02-20 23:39:45,261] Trial 3 finished with value: 1080.6916202243235 and parameters: {'iterations': 700, 'depth': 5, 'learning_rate': 0.05958389350068958, 'l2_leaf_reg': 7.71800699380605e-05, 'bagging_temperature': 0.2912291401980419}. Best is trial 3 with value: 1080.6916202243235.
[I 2026-02-20 23:39:47,583] Trial 4 finished with value: 1079.2293855418513 and parameters: {'iterations': 1400, 'depth': 4, 'learning_rate': 0.027010527749605478, 'l2_leaf_reg': 1.9826980964985924e-05, 'bagging_temperature': 0.45606998421703593}. Best is trial 4 with value: 1079.2293855418513.
[I 2026-02-20 23:39:49,066] Trial 5 finished with value: 1078.6885689867308 and parameters: {'iterations': 1700, 'depth': 4, 'learning_rate': 0.05748924681991978, 'l2_leaf_reg': 0.0021465011216654484, 'bagging_temperature': 0.046450412719997725}. Best is trial 5 with value: 1078.6885689867308.
[I 2026-02-20 23:39:54,075] Trial 6 finished with value: 1079.8867091778725 and parameters: {'iterations': 1400, 'depth': 4, 'learning_rate': 0.012476394272569451, 'l2_leaf_reg': 3.4671276804481113, 'bagging_temperature': 0.9656320330745594}. Best is trial 5 with value: 1078.6885689867308.
[I 2026-02-20 23:39:59,253] Trial 7 finished with value: 1078.604208939555 and parameters: {'iterations': 1700, 'depth': 5, 'learning_rate': 0.013940346079873234, 'l2_leaf_reg': 0.014391207615728067, 'bagging_temperature': 0.4401524937396013}. Best is trial 7 with value: 1078.604208939555.
[I 2026-02-20 23:40:08,229] Trial 8 finished with value: 1078.581202542344 and parameters: {'iterations': 600, 'depth': 6, 'learning_rate': 0.011240768803005551, 'l2_leaf_reg': 1.527156759251193, 'bagging_temperature': 0.2587799816000169}. Best is trial 8 with value: 1078.581202542344.
[I 2026-02-20 23:40:10,007] Trial 9 finished with value: 1079.9376516664884 and parameters: {'iterations': 1500, 'depth': 5, 'learning_rate': 0.05864129169696527, 'l2_leaf_reg': 0.0008325158565947976, 'bagging_temperature': 0.18485445552552704}. Best is trial 8 with value: 1078.581202542344.
[I 2026-02-20 23:40:23,054] Trial 10 finished with value: 1079.196809161962 and parameters: {'iterations': 2000, 'depth': 8, 'learning_rate': 0.023955920588449954, 'l2_leaf_reg': 3.9329516208822364, 'bagging_temperature': 0.6518665507781786}. Best is trial 8 with value: 1078.581202542344.
[I 2026-02-20 23:40:36,398] Trial 11 finished with value: 1080.441579449913 and parameters: {'iterations': 1100, 'depth': 7, 'learning_rate': 0.010381471637878005, 'l2_leaf_reg': 0.11289288985537722, 'bagging_temperature': 0.4298566837155936}. Best is trial 8 with value: 1078.581202542344.
[I 2026-02-20 23:40:40,851] Trial 12 finished with value: 1078.5528122110786 and parameters: {'iterations': 1900, 'depth': 6, 'learning_rate': 0.02091984682872805, 'l2_leaf_reg': 0.13511916433467072, 'bagging_temperature': 0.3571745195778723}. Best is trial 12 with value: 1078.5528122110786.
[I 2026-02-20 23:40:47,687] Trial 13 finished with value: 1079.464523936721 and parameters: {'iterations': 2000, 'depth': 7, 'learning_rate': 0.02439496850142924, 'l2_leaf_reg': 0.2524506280106374, 'bagging_temperature': 0.6202453298294528}. Best is trial 12 with value: 1078.5528122110786.
[I 2026-02-20 23:41:00,007] Trial 14 finished with value: 1079.9957574171092 and parameters: {'iterations': 900, 'depth': 8, 'learning_rate': 0.018910966366212888, 'l2_leaf_reg': 0.24862388147910555, 'bagging_temperature': 0.3476334304965827}. Best is trial 12 with value: 1078.5528122110786.
[I 2026-02-20 23:41:03,116] Trial 15 finished with value: 1077.4645089030244 and parameters: {'iterations': 1200, 'depth': 6, 'learning_rate': 0.038667209735311604, 'l2_leaf_reg': 7.63618462085716, 'bagging_temperature': 0.004445599374053422}. Best is trial 15 with value: 1077.4645089030244.
[I 2026-02-20 23:41:06,270] Trial 16 finished with value: 1077.7917500528924 and parameters: {'iterations': 1200, 'depth': 6, 'learning_rate': 0.03695683028951962, 'l2_leaf_reg': 9.172439837179562, 'bagging_temperature': 0.08620799663213846}. Best is trial 15 with value: 1077.4645089030244.
[I 2026-02-20 23:41:16,630] Trial 17 finished with value: 1078.9427871173282 and parameters: {'iterations': 1200, 'depth': 8, 'learning_rate': 0.03210367889788468, 'l2_leaf_reg': 9.040562002887725, 'bagging_temperature': 0.00315113665787127}. Best is trial 15 with value: 1077.4645089030244.
[I 2026-02-20 23:41:28,433] Trial 18 finished with value: 1083.7030376264588 and parameters: {'iterations': 900, 'depth': 9, 'learning_rate': 0.04104975015072629, 'l2_leaf_reg': 3.0903419157408147e-07, 'bagging_temperature': 0.08439480674424017}. Best is trial 15 with value: 1077.4645089030244.
[I 2026-02-20 23:41:31,075] Trial 19 finished with value: 1077.1642181508887 and parameters: {'iterations': 1300, 'depth': 6, 'learning_rate': 0.0405143679065449, 'l2_leaf_reg': 1.2557486015764376e-08, 'bagging_temperature': 0.8145901286801431}. Best is trial 19 with value: 1077.1642181508887.
[I 2026-02-20 23:41:33,926] Trial 20 finished with value: 1080.2232745218323 and parameters: {'iterations': 1600, 'depth': 7, 'learning_rate': 0.09099643200692288, 'l2_leaf_reg': 4.5971071227823905e-08, 'bagging_temperature': 0.9312546775349921}. Best is trial 19 with value: 1077.1642181508887.
[I 2026-02-20 23:41:37,701] Trial 21 finished with value: 1077.5857831169474 and parameters: {'iterations': 1300, 'depth': 6, 'learning_rate': 0.04084093951684193, 'l2_leaf_reg': 7.112883641038083e-06, 'bagging_temperature': 0.7918368266853275}. Best is trial 19 with value: 1077.1642181508887.
[I 2026-02-20 23:41:39,702] Trial 22 finished with value: 1078.6475599857881 and parameters: {'iterations': 1300, 'depth': 6, 'learning_rate': 0.08242047873638259, 'l2_leaf_reg': 8.645616518788633e-06, 'bagging_temperature': 0.827059871100533}. Best is trial 19 with value: 1077.1642181508887.
[I 2026-02-20 23:41:41,608] Trial 23 finished with value: 1078.7561247355104 and parameters: {'iterations': 1300, 'depth': 5, 'learning_rate': 0.04439780427927457, 'l2_leaf_reg': 1.7278865871666937e-08, 'bagging_temperature': 0.8139937055778315}. Best is trial 19 with value: 1077.1642181508887.
[I 2026-02-20 23:41:44,268] Trial 24 finished with value: 1079.5247621329206 and parameters: {'iterations': 1100, 'depth': 7, 'learning_rate': 0.08627001706131374, 'l2_leaf_reg': 2.3803087778760937e-06, 'bagging_temperature': 0.5624697941215455}. Best is trial 19 with value: 1077.1642181508887.
[I 2026-02-20 23:41:48,469] Trial 25 finished with value: 1077.4174849186807 and parameters: {'iterations': 1500, 'depth': 6, 'learning_rate': 0.04691268501805936, 'l2_leaf_reg': 1.5352920952519075e-07, 'bagging_temperature': 0.7976332727458727}. Best is trial 19 with value: 1077.1642181508887.
[I 2026-02-20 23:41:50,005] Trial 26 finished with value: 1079.5668689255144 and parameters: {'iterations': 1500, 'depth': 5, 'learning_rate': 0.07328355824335743, 'l2_leaf_reg': 1.3256509422645878e-07, 'bagging_temperature': 0.7482226680252511}. Best is trial 19 with value: 1077.1642181508887.
[I 2026-02-20 23:41:53,001] Trial 27 finished with value: 1079.6744981430807 and parameters: {'iterations': 1700, 'depth': 3, 'learning_rate': 0.016623642819080537, 'l2_leaf_reg': 1.395563007974341e-08, 'bagging_temperature': 0.8913318040738931}. Best is trial 19 with value: 1077.1642181508887.
[I 2026-02-20 23:41:55,769] Trial 28 finished with value: 1088.3387333672415 and parameters: {'iterations': 1500, 'depth': 8, 'learning_rate': 0.2961731536915935, 'l2_leaf_reg': 0.00018338740981859017, 'bagging_temperature': 0.9978600374336494}. Best is trial 19 with value: 1077.1642181508887.
[I 2026-02-20 23:42:03,217] Trial 29 finished with value: 1086.9937976181104 and parameters: {'iterations': 1000, 'depth': 9, 'learning_rate': 0.11276484916001187, 'l2_leaf_reg': 1.1317257008377515e-07, 'bagging_temperature': 0.5592366350810825}. Best is trial 19 with value: 1077.1642181508887.
Best CatBoost trial: {'iterations': 1300, 'depth': 6, 'learning_rate': 0.0405143679065449, 'l2_leaf_reg': 1.2557486015764376e-08, 'bagging_temperature': 0.8145901286801431}
Best CatBoost CV RMSE: 1077.1642181508887

In [ ]:
def get_oof_predictions(model_class, params, X, y, n_folds=5):
    kf = KFold(n_splits=n_folds, shuffle=True, random_state=RANDOM_STATE)
    oof_preds = np.zeros(len(y))
    models = []
    for train_idx, val_idx in kf.split(X):
        X_tr, X_val = X.iloc[train_idx], X.iloc[val_idx]
        y_tr, y_val = y.iloc[train_idx], y.iloc[val_idx]

        if model_class == xgb.XGBRegressor:
            # Move early_stopping_rounds to the constructor
            model = xgb.XGBRegressor(**params, tree_method='hist', early_stopping_rounds=50)
            model.fit(X_tr, y_tr, eval_set=[(X_val, y_val)], verbose=False)
        elif model_class == lgb.LGBMRegressor:
            # Removed verbose=False which caused the TypeError
            model = lgb.LGBMRegressor(**params)
            model.fit(X_tr, y_tr, eval_set=[(X_val, y_val)], callbacks=[lgb.early_stopping(50)])
        elif model_class == cb.CatBoostRegressor:
            model = cb.CatBoostRegressor(**params)
            model.fit(X_tr, y_tr, eval_set=(X_val, y_val), early_stopping_rounds=50, verbose=False)

        oof_preds[val_idx] = model.predict(X_val)
        models.append(model)
    return oof_preds, models

In [ ]:
xgb_oof, xgb_models = get_oof_predictions(xgb.XGBRegressor, study_xgb.best_params, X, y)
lgb_oof, lgb_models = get_oof_predictions(lgb.LGBMRegressor, study_lgb.best_params, X, y)
cat_oof, cat_models = get_oof_predictions(cb.CatBoostRegressor, study_cat.best_params, X, y)

Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[15]	valid_0's l2: 1.19831e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[11]	valid_0's l2: 1.13012e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[18]	valid_0's l2: 1.06704e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[21]	valid_0's l2: 1.18391e+06
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[15]	valid_0's l2: 1.24508e+06

In [ ]:
print('XGB OOF RMSE:', np.sqrt(mean_squared_error(y, xgb_oof)))
print('LGB OOF RMSE:', np.sqrt(mean_squared_error(y, lgb_oof)))
print('Cat OOF RMSE:', np.sqrt(mean_squared_error(y, cat_oof)))

XGB OOF RMSE: 1101.9561853845444
LGB OOF RMSE: 1079.3012432662583
Cat OOF RMSE: 1078.5789472051554

In [ ]:
blend_oof = (xgb_oof + lgb_oof + cat_oof) / 3
print('Simple blend OOF RMSE:', np.sqrt(mean_squared_error(y, blend_oof)))

Simple blend OOF RMSE: 1081.609026322199

In [ ]:
from sklearn.linear_model import LinearRegression
stack_X = np.column_stack([xgb_oof, lgb_oof, cat_oof])
stack_model = LinearRegression()
stack_model.fit(stack_X, y)
weights = stack_model.coef_
print('Optimal weights:', weights)

weighted_oof = stack_model.predict(stack_X)
print('Weighted blend OOF RMSE:', np.sqrt(mean_squared_error(y, weighted_oof)))

Optimal weights: [-0.26591413  0.54269291  0.74621637]
Weighted blend OOF RMSE: 1074.9501806832156

In [ ]:
# XGBoost
xgb_final = xgb.XGBRegressor(**study_xgb.best_params, tree_method='hist', random_state=RANDOM_STATE)
xgb_final.fit(X, y)

# LightGBM
lgb_final = lgb.LGBMRegressor(**study_lgb.best_params, random_state=RANDOM_STATE, verbosity=-1)
lgb_final.fit(X, y)

# CatBoost
cat_final = cb.CatBoostRegressor(**study_cat.best_params, random_state=RANDOM_STATE, verbose=False)
cat_final.fit(X, y)

# Predict on test
xgb_test_pred = xgb_final.predict(X_test)
lgb_test_pred = lgb_final.predict(X_test)
cat_test_pred = cat_final.predict(X_test)

# Blend with optimal weights
stack_test = np.column_stack([xgb_test_pred, lgb_test_pred, cat_test_pred])
final_pred = stack_model.predict(stack_test)

In [ ]:
submission = pd.DataFrame({
    'Item_Identifier': test['Item_Identifier'],
    'Outlet_Identifier': test['Outlet_Identifier'],
    'Item_Outlet_Sales': final_pred
})
submission.to_csv('BYE.csv', index=False)
print('Submission saved.')

Submission saved.

# Task
Refactor the machine learning pipeline for the Big Mart Sales dataset in "train.csv" and "test.csv" by renaming generic columns (X1-X11, Y) to descriptive names: `Item_Identifier`, `Item_Weight`, `Item_Fat_Content`, `Item_Visibility`, `Item_Type`, `Item_MRP`, `Outlet_Identifier`, `Outlet_Establishment_Year`, `Outlet_Size`, `Outlet_Location_Type`, `Outlet_Type`, and `Item_Outlet_Sales`.

The task includes updating all subsequent steps: standardizing fat content labels, imputing missing `Item_Weight` and `Outlet_Size`, engineering features like `Outlet_Age` and target-encoded identifiers, and fine-tuning XGBoost, LightGBM, and CatBoost models using Optuna. Finally, generate a weighted ensemble prediction and save the results to "BYE.csv".

## Identify and Rename Columns

### Subtask:
Rename the generic column names X1-X11 and Y to descriptive names in both train and test DataFrames.

**Reasoning**:
I will rename the generic columns in the train and test DataFrames to descriptive names using the provided mapping to improve clarity and fix previous errors caused by incorrect column names.

In [ ]:
column_mapping = {
    'X1': 'Item_Identifier',
    'X2': 'Item_Weight',
    'X3': 'Item_Fat_Content',
    'X4': 'Item_Visibility',
    'X5': 'Item_Type',
    'X6': 'Item_MRP',
    'X7': 'Outlet_Identifier',
    'X8': 'Outlet_Establishment_Year',
    'X9': 'Outlet_Size',
    'X10': 'Outlet_Location_Type',
    'X11': 'Outlet_Type',
    'Y': 'Item_Outlet_Sales'
}

train.rename(columns=column_mapping, inplace=True)
test.rename(columns=column_mapping, inplace=True)

print("Train columns:", train.columns.tolist())
print("Test columns:", test.columns.tolist())
train.head()